- src/frecent_paths.rs
- src/main.rs
Also order things more consistently; it's always least-frecent ->
more-frecent in the paths ocming out of frecent_paths, and thus main
should take 'last'.
This is primarily because '-i' and 'z' (with no args) order them as
most-important-last since the bottom of the list is more immediately
reachable for a viewer from the input prompt.
Fixes #18
> frecent_paths: dedupe entries by path

- README.md
- src/lib.rs
- src/main.rs
- src/supported_shells.rs
- tests/integ.rs
There's no major reason to do this, it just seems like a slightly nicer
ux
>  init: move into subcommand

- src/main.rs
- tests/src/harness/testshell/mod.rs
- tests/src/integ.rs
The messup with flag handling I had in #30 resulted in some silly behavior (printing an error and zapping on 'z'). This would have caused that behavior to be a little less silly.
It also adds an integ test which wouldn't have caught it 🤷‍
>  zsh/bash: handle more error return codes

- src/frecency.rs
- src/importers/mod.rs
- src/main.rs
- tests/src/bench.rs
- tests/src/harness/autojumpers/fasd.rs
- tests/src/harness/autojumpers/pazi.rs
- tests/src/harness/mod.rs
- tests/src/harness/shells.rs
- tests/src/harness/testshell/mod.rs
- tests/src/integ.rs
🔥 🚗 ⏩ ⏩ 💨 
Before:
```
$ cargo bench --features=nightly cd_bench_nojumper
running 2 tests
test bench::cd_bench_nojumper_bash        ... bench:   5,886,133 ns/iter (+/- 3,493,799)
test bench::cd_bench_nojumper_zsh         ... bench:  14,084,141 ns/iter (+/- 9,686,470)
```
After:
```
$ cargo bench --features=nightly cd_bench_nojumper
running 2 tests
test bench::cd_bench_nojumper_bash        ... bench:      86,638 ns/iter (+/- 4,373)
test bench::cd_bench_nojumper_zsh         ... bench:      32,791 ns/iter (+/- 1,888)
```
Sorry about throwing in the noise of `cargo fmt` too, just ignore that commit for reviewing. The first two are the important ones that make real changes.
> Optimized those benchmarks *good*

- src/lib.rs
- src/main.rs
- src/shells/bash.rs
- src/shells/mod.rs
- src/shells/zsh.rs
- src/supported_shells.rs
- tests/src/integ.rs
This moves giant const strings off into functions where they look less
egregious.
> main: split out 'shells' module for init

- src/frecent_paths.rs
Should improve pazi's ability to find matches in a fresh database!
I replicated the debug output so we can still see the paths it considered when generating the completion.
> frecent_paths: remove frecency cutoff

- src/shells/bash.rs
> bash: read $PROMPT_COMMAND without interpreting escapes (raw mode)

- src/main.rs
This is something that bugged me; I think this padding behavior is
preferable.
> main: pad default output evenly

- .gitmodules
- .travis.yml
- tests/src/bench.rs
- tests/src/benches.csv
- tests/src/harness/autojumpers/autojump.rs
- tests/src/harness/autojumpers/fasd.rs
- tests/src/harness/autojumpers/mod.rs
- tests/src/harness/autojumpers/pazi.rs
- tests/src/harness/mod.rs
This is part of #47; adding 'autojump' to the benchmark harness was fairly straightforwards, so this should be easy to review.
I'll redo benchmark results and analysis in a separate PR once I've added the 3rd contestant.
>  tests/benches: add 'autojump' benches 

- README.md
I noticed a missing parenthesis in the README, made a fork to fix it, and upon seeing the unrendered markdown got a tad carried away.
There was a missing parenthesis under "What makes pazi different from
*X*". Add it.
URLs mixed inline with human-readable text can reduce readability of the
unrendered markdown. Move URLs to references at the end of the document.
The README was a mix of fixed character lines and one paragraph per
line. Reflow all text to be max 80 characters per line.
> README: stick to 80 char columns, move links to end, add closing paren

- src/interactive.rs
- src/main.rs
- src/pazi_result.rs
- src/shells/bash.rs
- src/shells/zsh.rs
Change interactive.filter to return an Option<String> in the success
case, with Ok(None) representing the user returned an empty string.
Modify main.rs to do nothing when this happens.
Prompted by me seeing the following when I pressed enter without any input on `z -i`:
```
derek@proton ~> z -i ign
pazi_cd:cd:7: no such file or directory: unable to parse selection: cannot parse integer from empty string
```
> src/interactive: correctly handle empty string

- src/main.rs
When a tty receives a ctrl-c, it sends SIGINT to the foreground process group (i.e., foreground process and its children). When handling Pazi output, though, we don't want to SIGINT the function running Pazi, just Pazi itself.
See discussion on #55.
Fixes #54. Closes #55.
> src/main: Put Pazi in its own process group when running interactively

- Cargo.lock
This squashes an "unnecessary mut" warning from `chan_select!` at least.
> Cargo.lock: Update

- tests/Cargo.lock
- tests/Cargo.toml
- tests/build.rs
- tests/src/bench.rs
- tests/src/benches.csv
- tests/src/harness/mod.rs
- tests/src/harness/shells.rs
- tests/src/harness/testshell/mod.rs
- tests/src/integ.rs
This implements a way for benchmarks to indicate that the testshell
should wait for any forked processes to end.
This is helpful for `z` and `autojump`, which add directories by forking
off into the background.
This will allow benchmarking the speed of those operations, and to make
the benchmarks not flaky (e.g. rcd + jump can flake without a wait in
between).
The implementation is done by using cgroups to keep track of pids,
assuming a shell during normal operation will only have one pid, and
then going from there.
There are a cople caveats:
1. This requires cgroups-v2 or hybrid for tracking processes
(cgroup.procs) vs threads.
1. The overhead introduced by this is difficult to measure perfectly; it
has no significant impact in the case where children aren't forked,
but when children …
> tests/bench: allow 'wait'ing for forking jumpers

- .gitmodules
- tests/build.rs
- tests/src/bench.rs
- tests/src/benches.csv
- tests/src/harness/autojumpers/mod.rs
- tests/src/harness/autojumpers/z.rs
- tests/src/harness/mod.rs
`z` is actually quite fast. It's still slightly slower than pazi, but it's scarily close.
```
test bench::cd_bench_autojump_bash            ... bench:  19,589,749 ns/iter (+/- 10,152,476)
test bench::cd_bench_autojump_zsh             ... bench:  21,986,256 ns/iter (+/- 10,536,365)
test bench::cd_bench_fasd_bash                ... bench:  15,264,866 ns/iter (+/- 4,113,044)
test bench::cd_bench_fasd_zsh                 ... bench:  13,967,354 ns/iter (+/- 1,495,894)
test bench::cd_bench_nojumper_bash            ... bench:      94,704 ns/iter (+/- 10,146)
test bench::cd_bench_nojumper_zsh             ... bench:      40,872 ns/iter (+/- 8,339)
test bench::cd_bench_pazi_bash                ... bench:   1,142,437 ns/iter (+/- 45,770)
test bench::cd_bench_pazi_zsh                 ... bench: …
```
>  benches: add 'z' to benches

- src/frecency.rs
- src/frecent_paths.rs
- src/interactive.rs
- src/main.rs
`frecency` changes:
- Always returns results sorted by most to least frecent
- Always returns references to the path strings it owns
`frecent_paths` changes:
- Paths are iterated over in order from most to least frecent
- Always returns an iterator over paths that it owns
- Paths are copied at most once
Benchmarks (Core 2 Duo, spinning rust): https://p.brod.es/#/view/Skxq8Q_j/I80JjCqchcxH4fC3y.updmHMMhzf5lg0
Possible improvements:
- Benchmarking jump where paths must be removed vs jump where paths may not be removed
- Allocating path strings in an arena so that no copying is needed
Personally, I'm happy with this, but I'd like to clean up the git history before merging.
Closes #32.
> Lazy pruning of deleted directories

- src/main.rs
- src/shells/bash.rs
- src/shells/zsh.rs
- tests/src/integ.rs
This fixes #70.
Prior to this change, there was a mix of subcommands and flags that were
all mutually-exclusive behaviours.
This ended up being a bit awkward and made some configurations
ambiguous.
This moves to a much nicer structure. There are global flags (right now
just debug), and then there are subcommands for each distinct
mode of operation.
For ease of migration, the previous logic still remains, but it can be
safely deleted after another release or so to allow migration.
>  main: move 'jump' and 'visit' to subcommands 

- .gitmodules
- .travis.yml
- tests/Cargo.lock
- tests/Makefile
- tests/README.md
- tests/build.rs
- tests/src/bench.rs
- tests/src/benches.csv
- tests/src/harness/autojumpers/autojump.rs
- tests/src/harness/autojumpers/fasd.rs
- tests/src/harness/autojumpers/jump.rs
- tests/src/harness/autojumpers/mod.rs
- tests/src/harness/autojumpers/z.rs
- tests/src/harness/mod.rs
- tests/src/harness/shells.rs
- tests/src/harness/testshell/mod.rs
- tests/src/integ.rs
Closes #82.
Preliminary results:
```
test bench::cd_bench_autojump_bash            ... bench:  61,206,943 ns/iter (+/- 3,793,731)
test bench::cd_bench_autojump_zsh             ... bench:  62,042,056 ns/iter (+/- 4,531,715)
test bench::cd_bench_fasd_bash                ... bench:  22,266,885 ns/iter (+/- 3,308,704)
test bench::cd_bench_fasd_zsh                 ... bench:  19,945,300 ns/iter (+/- 2,400,944)
test bench::cd_bench_jump_bash                ... bench:   2,739,991 ns/iter (+/- 610,425)
test bench::cd_bench_jump_zsh                 ... bench:   2,600,361 ns/iter (+/- 564,764)
test bench::cd_bench_nojumper_bash            ... bench:     188,041 ns/iter (+/- 54,984)
test bench::cd_bench_nojumper_zsh             ... bench:      37,384 ns/iter (+/- 11,962)
test …
```
> Benchmark against jump

- Cargo.lock
- Cargo.toml
- src/interactive.rs
- src/main.rs
This commit replaces the [`chan`](https://crates.io/crates/chan) and [`chan-signal`](https://crates.io/crates/chan-signal) crates, which are deprecated, with the [`crossbeam-channel`](https://crates.io/crates/crossbeam-channel) and and [`signal-hook`](https://crates.io/crates/signal-hook) crates.
This is my first Rust PR.  I've built this with `cargo build` and tested it with `cargo test` and by running the binary (just prints the frecency list), but I have not otherwise validated the change.
> interactive: chan and chan-signal are deprecated

- tests/src/harness/testshell/mod.rs
This avoids a regression in nightly (reported
https://github.com/rust-lang/rust/issues/55775).
It makes sense to pass through the path after 'env_clear' anyway though
given shells are just run by bin name, not full bin path.
> tests: explicitly pass through PATH

- .travis.yml
- src/main.rs
- tests/Cargo.lock
- tests/src/integ.rs
Fixes #91 
This works for me (x86_64 linux) and @lclarkmichalek (x86_64 OSX), so I think this change should be fine.
> Conditionally use Linux or OSX libc definitions

- tests/Makefile
Prevents accidental stale pazi builds when doing benches.
This may or may not be driven by real-life confusion.
> tests: Always build pazi for makefile targets

- README.md
- src/main.rs
- src/shells/zsh.rs
- tests/src/harness/autojumpers/pazi.rs
Added zsh shell completion
Addresses https://github.com/euank/pazi/issues/10
Here is what it looks like:
[![asciicast](https://asciinema.org/a/225721.svg)](https://asciinema.org/a/225721)
I am not sure whether this is how you envisioned the shell completion. This could be more of a minimum viable implementation of the idea. 
- One possibly better way to implement the completion instead of outputting the whole paths would be to output the part of the path that matches the input along with the path as the description.
- Another improvement I could see would be to have the complete subcommand have further subcommands for each supported shell, each outputting in a different way as needed by the shell?
- Or the other way around, output in a specific format and do the heavy lifting in the …
> Added shell completion for zsh

- tests/.travis/hack.sh
- tests/Cargo.lock
dependabot isn't doing a good job on getting these updated correctly right now. One manual pass seems easier.
> Update test deps

- src/shells/bash.rs
- src/shells/fish.rs
- src/shells/zsh.rs
Pazi currently does not seem to use forks in its `precmd/preexec/chpwd` functions. This, however fast pazi might be, should result in a loss of performance.
This PR adds forking to the `__pazi_add_dir` functions for all shells. Subshells are explicitly avoided as they are not very performant.
> Use forks in __pazi_add_dir

- tests/flake.nix
- tests/src/bench.rs
- tests/src/benches.csv
- tests/src/harness/autojumpers/mod.rs
- tests/src/harness/autojumpers/zoxide.rs
- tests/src/harness/mod.rs
This lets us version them the same way we do zsh and bash. It does add another dependency to runs tests and benches, but it actually removes the go dependency, so it's neutral I guess?
It also lets us lean on the nixpkgs's ecosystem for pulling in other benchmark targets without having to figure out how to build each one ourselves or such.
Preliminary benchmark results for zoxide vs everything (I'll update the real benchmark doc separately. I was running other stuff on  my computer with these benches, so it's less controlled than the benchmark doc's ones are):
```
test bench::cd_bench_autojump_bash            ... bench:  46,916,012 ns/iter (+/- 3,486,373)
test bench::cd_bench_autojump_zsh             ... bench:  45,835,440 ns/iter (+/- 2,711,631)
test bench::cd_bench_fasd_bash …
```
> tests: add zoxide to benchmarks

- README.md
- docs/Autojumpers.md
We can add features, etc, later as more columns, but for now I wanted to
move the list somewhere I can reference it.
The readme doesn't feel like the right place for an exhaustive list of
em.
> docs: add table of other autojumpers, reference zoxide from readme

- src/main.rs
FreeBSD 14's errno can be retrieved using the following function:
extern int	* __error();
This is documented in the intro(2) manual page, seen here: https://man.freebsd.org/cgi/man.cgi?query=errno&apropos=0&sektion=0&manpath=FreeBSD+14.0-RELEASE&arch=default&format=html
Fixes: https://github.com/euank/pazi/issues/445
> errno: support FreeBSD

- tests/flake.lock
- tests/flake.nix
Just some rote maintenance; tests pass locally, and if CI agrees this seems safe to merge
> tests: nix flake update

- Cargo.toml
- ChangeLog.md
- tests/Cargo.lock
Time for a release!
Changelog entry:
This release contains a small number of bugfixes and improvements, but no major changes.
* New database entries are added in a background process now, improving performance in some cases.
* A manpage is now included in 'packaging/man/pazi.1'. Package maintainers are included to include this in pazi's package.
* Various dependency updates.
> Release v0.5.0 :zap::zap:
